import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import ReduxProvider from '@/store/ReduxProvider';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: ReactNode;
}>) {
  return (
    <ReduxProvider>
      {' '}
      <html lang="en">
        <body className={`${roboto.variable}`}>
          {children}
          {auth}
        </body>
      </html>
    </ReduxProvider>
  );
}
