import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import ReduxProvider from '@/store/ReduxProvider';
import { Bounce, ToastContainer } from 'react-toastify';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: ReactNode;
}>) {
  return (
    <ReduxProvider>
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        transition={Bounce}
      />
      <html lang="en">
        <body className={`${roboto.variable}`}>
          {children}
          {auth}
        </body>
      </html>
    </ReduxProvider>
  );
}
