import { CourseType } from './shared-types/sharedTypes';

export const courses: CourseType[] = [
  {
    _id: 1,
    name: 'Йога',
    cover: '/img/yoga.png',
    description: '',
    directions: [''],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: 2,
    name: 'Стретчинг',
    cover: '/img/stretching.png',
    description: '',
    directions: [''],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: 3,
    name: 'Фитнес',
    cover: '/img/fitness.png',
    description: '',
    directions: [''],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: 4,
    name: 'Степ-аэробика',
    cover: '/img/step-aerobics.png',
    description: '',
    directions: [''],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: 5,
    name: 'Бодифлекс',
    cover: '/img/bodyflex.png',
    description: '',
    directions: [''],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
];
