import { BannerCourseType, CourseType } from './shared-types/sharedTypes';

export const courses: CourseType[] = [
  {
    _id: '1',
    name: 'Йога',
    cover: '/img/yoga.png',
    description: '',
    directions: [
      'Йога для новичков',
      'Кундалини-йога',
      'Хатха-йога',
      'Классическая йога',
      'Йогатерапия',
      'Аштанга-йога',
    ],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: '2',
    name: 'Стретчинг',
    cover: '/img/stretching.png',
    description: '',
    directions: [
      'Йога для новичков',
      'Кундалини-йога',
      'Хатха-йога',
      'Классическая йога',
      'Йогатерапия',
      'Аштанга-йога',
    ],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: '3',
    name: 'Фитнес',
    cover: '/img/fitness.png',
    description: '',
    directions: [
      'Йога для новичков',
      'Кундалини-йога',
      'Хатха-йога',
      'Классическая йога',
      'Йогатерапия',
      'Аштанга-йога',
    ],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: '4',
    name: 'Степ-аэробика',
    cover: '/img/step-aerobics.png',
    description: '',
    directions: [
      'Йога для новичков',
      'Кундалини-йога',
      'Хатха-йога',
      'Классическая йога',
      'Йогатерапия',
      'Аштанга-йога',
    ],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
  {
    _id: '5',
    name: 'Бодифлекс',
    cover: '/img/bodyflex.png',
    description: '',
    directions: [
      'Йога для новичков',
      'Кундалини-йога',
      'Хатха-йога',
      'Классическая йога',
      'Йогатерапия',
      'Аштанга-йога',
    ],
    fitting: [''],
    difficulty: '/img/difficulty.png',
    durationInDays: 25,
    dailyDurationInMinutes: {
      from: 20,
      to: 50,
    },
    workouts: [''],
  },
];

export const bannersCourses: BannerCourseType[] = [
  { _id: '1', banner: '/img/card-1.png', bgc: '#FFC700' },
  { _id: '2', banner: '/img/card-2.png', bgc: '#2491D2' },
  { _id: '3', banner: '/img/card-3.png', bgc: '#F7A012' },
  { _id: '4', banner: '/img/card-4.png', bgc: '#FF7E65' },
  { _id: '5', banner: '/img/card-5.png', bgc: '#7D458C' },
];
